---
title: "Research"
---

-   [**The Effect of COVID-19 Lockdown and the Subsequent Re-opening on Consumption in Iran**](https://link.springer.com/article/10.1007%2Fs11150-021-09557-8), with Abolmohsen Valizadeh, *Review of Economics of the Household*, 19, Pages 373--397, June 2021. [download link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3662980)

-   [**Production Efficiency and Self-enforcement in Value-Added Tax: Evidence from State-level Reform in India**](https://doi.org/10.1016/j.jdeveco.2020.102462), with Oceane Briand, *Journal of Development Economics*, Volume 144, May 2020, 102462. [download link](https://www.dropbox.com/s/n1geb256hfspahr/PE%20VAT.pdf?dl=0)

-   [**Value-Added Tax, Input-Output Linkages, and Informality**](https://onlinelibrary.wiley.com/doi/10.1111/ecca.12310), *Economica*, Volume 87, Issue 347, July 2020, Pages 813-843. [download link](https://www.dropbox.com/s/7d2ky4v1do9v2w6/VAT%20IO%20linkage%20and%20informality.pdf?dl=0)

-   [**Trade Credit and Access to Finance of Retailers in Ethiopia**](https://academic.oup.com/jae/advance-article-abstract/doi/10.1093/jae/ejz018/5433371?redirectedFrom=fulltext), with Thorsten Beck and Burak Uras, *Journal of African Economies*, Volume 29, Issue 2, March 2020, Pages 146--172. [download link](https://www.dropbox.com/s/4blvin1e4xusjx9/BeckHoseiniUras2020.pdf?dl=0)

-   [**Finance, Law, and Poverty: Evidence from India**](https://www.sciencedirect.com/science/article/pii/S0929119918308022), with Meghana Ayyagari and Thorsten Beck, *Journal of Corporate Finance*, Volume 60, February 2020, 101515. [Vox column summary](http://www.voxeu.org/article/migrating-out-poverty-role-finance), [download link](https://www.dropbox.com/s/rps5qr8ryzd7g02/Finance%20and%20Poverty%20in%20India-072319-MA.pdf?dl=0)

## Working Papers
- [__Marriage and Employment Returns to Female Education__](https://www.dropbox.com/s/pf8xbseis3302g0/Returns_to_education.pdf?dl=0)

- [__Compulsory Military Service and Lifetime Earnings: A Structural Estimation__](https://www.dropbox.com/s/d9vlpd3rzsirxc5/Hoseini_Sabouri.pdf?dl=0), with Ehsan Sabouri

- [__Inequality with Top Incomes in Iran__](https://www.dropbox.com/s/neftgk0zgaxdeq1/Topincomes%20March%202023.pdf?dl=0) with Zahra Shamlou and Djavad Salehi-Esfahani

- [__How do shared experiences of economic shocks impact refugees and host communities? Evidence from Afghan refugees in Iran__](https://documents.worldbank.org/en/publication/documents-reports/documentdetail/311771643289939369/how-do-shared-experiences-of-economic-shocks-impact-refugees-and-host-communities-evidence-from-afghan-refugees-in-iran), with Mahsa Jahan-Dideh, _World Bank Policy Research working paper, no. WPS 9915_

-   [**Emergency Loans and Consumption: Evidence from COVID-19 in Iran**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3683572), with Thorsten Beck, *Covid Economics*, 45, 28 August 2020: 111-146. [Vox column summary](https://voxeu.org/article/emergency-loans-and-consumption-evidence-covid-19-iran)

-   [**Informality and Access to Finance: Evidence from India**](https://www.dropbox.com/s/yc2z6ufmkbpbxee/Informality%20and%20access%20to%20finance%20October2019.pdf?dl=0), with Thorsten Beck

-   [**Misreporting of VAT and Optimal Enforcement**](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2505998)

